# Generated by Django 2.2.4 on 2019-10-26 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(choices=[('small', 'Малый'), ('medium', 'Средний'), ('large', 'Крупный')], default='medium', max_length=30)),
                ('age', models.IntegerField(blank=True)),
                ('units', models.CharField(choices=[('month', 'мес'), ('year', 'год')], default='year', max_length=30)),
                ('photo', models.URLField(blank=True, max_length=500)),
                ('hair', models.CharField(choices=[('short', 'Короткошерстный'), ('long', 'Длинношерстный'), ('hairless', 'Голый')], default='short', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='mongrel', max_length=40)),
                ('desc', models.TextField(default='Perfect breed for..', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('price', models.IntegerField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog')),
                ('kennel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Kennel')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
