# Generated by Django 2.2.4 on 2019-10-29 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCIGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default='')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.DogBreed'),
        ),
        migrations.AddField(
            model_name='dog',
            name='kennel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.Kennel'),
        ),
        migrations.AddField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('М', 'boy'), ('Ж', 'girl')], default='Ж', max_length=50),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='hair',
            field=models.CharField(choices=[('короткая шерсть', 'short'), ('клинная шерсть', 'long'), ('без шерсти', 'hairless')], default='короткая шерсть', max_length=50),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='photo',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='size',
            field=models.CharField(choices=[('Маленького размера', 'small'), ('Среднего размера', 'medium'), ('Крупного размера', 'large')], default='Среднего размера', max_length=30),
        ),
        migrations.AddField(
            model_name='kennel',
            name='about',
            field=models.CharField(default='', max_length=1000, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='kennel',
            name='breeds',
            field=models.ManyToManyField(related_name='kennel_breeds', to='dogs.DogBreed'),
        ),
        migrations.AddField(
            model_name='kennel',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kennel',
            name='photo',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ad',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ad',
            name='dog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='kennel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.Kennel'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='hair',
            field=models.CharField(choices=[('короткая шерсть', 'short'), ('клинная шерсть', 'long'), ('без шерсти', 'hairless')], default='короткая шерсть', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(default='Малыш', max_length=50),
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('Маленького размера', 'small'), ('Среднего размера', 'medium'), ('Крупного размера', 'large')], default='Среднего размера', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='units',
            field=models.CharField(choices=[('мес.', 'month'), ('г.', 'year')], default='Год', max_length=30),
        ),
        migrations.AlterField(
            model_name='dogbreed',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='kennel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dogbreed',
            name='FCI_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.FCIGroup'),
        ),
    ]
