# Generated by Django 2.2.4 on 2019-10-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_auto_20191029_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(blank=True, choices=[('Метис', 'mongrel'), ('Йоркширский терьер', 'york'), ('Такса', 'taksa'), ('Лабрадор-ретривер', 'labritriever'), ('Чихуахуа', 'chihuahua'), ('Пудель', 'poodle'), ('Бишон', 'bishon')], max_length=50, null=True),
        ),
    ]
